// <auto-generated />
namespace Library.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initializebookcategorypublishhouseartisttables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initializebookcategorypublishhouseartisttables));
        
        string IMigrationMetadata.Id
        {
            get { return "201906101731209_initialize book, category, publishhouse, artist tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
